{% set name = "listen" %}
{% set version = "3.3.0" %}

package:
  name: rb-{{ name|lower }}
  version: {{ version }}

source:
  url: https://rubygems.org/downloads/{{ name }}-{{ version }}.gem
  sha256: 0f91c5287358feee216f41e00a5b70ec125dd5c1d8fe51a014e864a29842041f

build:
  noarch: generic
  number: 0
  script:
    - gem install -N -l -V --norc --ignore-dependencies {{ name }}-{{ version }}.gem
    - gem unpack {{ name }}-{{ version }}.gem
  skip: {{ win }}

requirements:
  host:
    - ruby
  run:
    - ruby
    - rb-rb-fsevent >=0.9.4,<1
    - rb-rb-inotify >=0.9.7,<1
    - rb-ruby_dep >=1.2,<2

test:
  commands:
    - ruby -r {{ name }} -e 'exit 0'

about:
  home: https://rubygems.org/gems/{{ name }}
  license: MIT
  license_family: MIT
  license_file: {{ name }}-{{ version }}/LICENSE.txt
  summary: The Listen gem listens to file modifications and notifies you about the changes. Works everywhere!

  doc_url: http://www.rubydoc.info/gems/{{ name }}
  dev_url: https://github.com/guard/{{ name }}

extra:
  recipe-maintainers:
    - sodre
