travis:
  secure:
    BINSTAR_TOKEN: Wu3nl7MWUlVZdA+bucoy8ZIVwFi1EOCdEbh7k/JWa6qLZYbPU6O8maMsgig+cRrvh7RivJtjKq9bk/jEvaVhqOJ83ZDr8EujIv3EMriOIj6HqwXrC/Wsxd2nSTyGiqUoVjBEvm82j0FJvRuiyR4HTrLSg5xLJq6QmP025vBcpF+IicYrFX2dugCI96p2lPrwF4vJN3Mz0N/qpTYgrDB+bliwvCotKFdnyMtNqyXtoiAY3+zloSCHJq9hObvUhiLSD7O/MG2Mh/XVJKswMI3K7ljjlniXnTpeHoeH1XpOz7VG2O2ZGaBNGZshNFEiOSrX9ROgd6qW56B748pv2wag96TTnCwYRbc74xt33PgvQwhiLmDnf27omkJ7cfj5strC6gN7wm7IDzKHkYOPo/EEujS6WFxOTxuEXo7sxos1/CAp6MOpx5z6cpTdnbYQV5e9Utpty8tDYCEdFVSSW54hv/qXZCen79rmfrqRswAG8s4Y1xq2wJWBu51ruQJALGiyD/YKgBEqdvDSQzVCjN/Wed0wlgzXi+tz3yVv1K9fEgWQQoPEOTwVxxWl9RMpMt1SODtA9nzQLlnLxw29nyOj7dDT/eSo7tPybBFQsj8ePUki9NS08Psw6yG06T73cmVynPdMo8/g8p5sDj/xDWu8D50CC2GhNcP7Rd1aEDBACz8=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: false
